#!/usr/bin/python
import RPi.GPIO as GPIO
import time
import smtplib
 
#GPIO SETUP
channel = 21
GPIO.setmode(GPIO.BCM)
GPIO.setup(channel, GPIO.IN)
 
def callback(channel):
        if GPIO.input(channel):
                print ("no water detected")
        

                """content = "kys"

                mail = smtplib.SMTP("smtp.gmail.com",587)

                mail.ehlo()

                mail.starttls()

                mail.login("byangves@gmail.com", "Yangyifan02$")

                mail.sendmail("byangves@gmail.com", "ojulich@ves.org", content)

                mail.close()""" 


        else:
                print ("water detected")

        time.sleep(900)
 
GPIO.add_event_detect(channel, GPIO.BOTH, bouncetime=300)  # let us know when the pin goes HIGH or LOW
GPIO.add_event_callback(channel, callback)  # assign function to GPIO PIN, Run function on change
 
# infinite loop
while True:
        time.sleep(1)
        callback(21)
        

